"""
news_images.py

Prepares up to 2 images for a crypto news post:

1. The article's original/primary news image.
2. The crypto's Binance asset logo.

If either image cannot be found, it is simply skipped.

No image is generated by AI.
"""

import os
import re
import tempfile
from pathlib import Path
from urllib.parse import urlparse

import requests


BINANCE_ASSET_LOGO_URL = (
    "https://www.binance.com/"
    "bapi/asset/v1/public/asset-service/product/currency"
)

TIMEOUT = 15


def _safe_extension(content_type: str, url: str) -> str:
    """Return a safe image extension."""

    content_type = (
        content_type or ""
    ).lower()

    if "png" in content_type:
        return ".png"

    if "webp" in content_type:
        return ".webp"

    if "gif" in content_type:
        return ".gif"

    if "jpeg" in content_type or "jpg" in content_type:
        return ".jpg"

    path = urlparse(url).path.lower()

    for ext in (
        ".jpg",
        ".jpeg",
        ".png",
        ".webp",
        ".gif",
    ):
        if path.endswith(ext):
            return ext

    return ".jpg"


def _download_image(
    url: str,
    prefix: str,
) -> str | None:
    """Download one image and return its local path."""

    if not url:
        return None

    try:

        response = requests.get(
            url,
            headers={
                "User-Agent": (
                    "Mozilla/5.0 "
                    "NewsPostBot/1.0"
                )
            },
            timeout=TIMEOUT,
            stream=True,
        )

        response.raise_for_status()

        content_type = response.headers.get(
            "Content-Type",
            "",
        )

        if not content_type.lower().startswith(
            "image/"
        ):
            return None

        extension = _safe_extension(
            content_type,
            url,
        )

        fd, path = tempfile.mkstemp(
            prefix=f"{prefix}_",
            suffix=extension,
        )

        os.close(fd)

        with open(path, "wb") as file:

            total = 0

            for chunk in response.iter_content(
                chunk_size=64 * 1024
            ):

                if not chunk:
                    continue

                total += len(chunk)

                # Avoid unexpectedly huge files.
                if total > 10 * 1024 * 1024:
                    raise ValueError(
                        "Image is larger than 10 MB."
                    )

                file.write(chunk)

        return path

    except Exception as err:

        print(
            f"[news_images] image download failed: "
            f"{url} -> {err}"
        )

        return None


def _get_article_image_urls(
    article: dict,
) -> list[str]:
    """
    Return possible article image URLs.

    Priority:
    1. Finnhub image
    2. article image fields
    3. image list fields
    """

    urls = []

    possible_fields = (
        "image",
        "image_url",
        "imageUrl",
        "thumbnail",
    )

    for field in possible_fields:

        value = article.get(field)

        if isinstance(value, str):
            value = value.strip()

            if value:
                urls.append(value)

    # Some feeds may provide multiple images.
    for field in (
        "images",
        "image_urls",
        "imageUrls",
    ):

        value = article.get(field)

        if isinstance(value, list):

            for item in value:

                if isinstance(item, str):
                    item = item.strip()

                    if item:
                        urls.append(item)

    # Remove duplicates while preserving order.
    result = []

    seen = set()

    for url in urls:

        if url not in seen:

            seen.add(url)
            result.append(url)

    return result


def get_binance_asset_logo_url(
    ticker: str,
) -> str | None:
    """
    Get the Binance asset logo URL.

    Binance's public asset service exposes asset
    symbols together with their image URLs.
    """

    if not ticker:
        return None

    ticker = ticker.upper().strip()

    try:

        response = requests.get(
            BINANCE_ASSET_LOGO_URL,
            timeout=TIMEOUT,
        )

        response.raise_for_status()

        data = response.json()

    except Exception as err:

        print(
            f"[news_images] Binance logo lookup failed: "
            f"{err}"
        )

        return None

    assets = data.get("data") or []

    for asset in assets:

        if not isinstance(asset, dict):
            continue

        symbol = str(
            asset.get("asset", "")
        ).upper()

        if symbol != ticker:
            continue

        logo = (
            asset.get("pic")
            or asset.get("icon")
            or asset.get("logo")
        )

        if logo:
            return str(logo)

    return None


def prepare_post_images(
    article: dict,
    ticker: str,
) -> list[str]:
    """
    Prepare the final image list.

    Image 1:
        Article's original image.

    Image 2:
        Binance crypto logo.

    Returns local file paths.
    """

    paths = []

    # ---------------------------------------------------------
    # IMAGE 1 — NEWS IMAGE
    # ---------------------------------------------------------

    article_urls = _get_article_image_urls(
        article
    )

    for url in article_urls:

        path = _download_image(
            url,
            "news_image",
        )

        if path:

            print(
                f"[news_images] news image ready: "
                f"{path}"
            )

            paths.append(path)

            # Only ONE news image.
            break

    # ---------------------------------------------------------
    # IMAGE 2 — CRYPTO LOGO
    # ---------------------------------------------------------

    logo_url = get_binance_asset_logo_url(
        ticker
    )

    if logo_url:

        logo_path = _download_image(
            logo_url,
            "crypto_logo",
        )

        if logo_path:

            print(
                f"[news_images] crypto logo ready: "
                f"{logo_path}"
            )

            # Avoid duplicate URL/path if somehow same.
            if logo_path not in paths:
                paths.append(logo_path)

    print(
        f"[news_images] prepared "
        f"{len(paths)} image(s) for ${ticker}"
    )

    return paths


def cleanup_images(
    paths: list[str],
) -> None:
    """Delete temporary downloaded images."""

    for path in paths:

        if not path:
            continue

        try:

            Path(path).unlink(
                missing_ok=True
            )

        except Exception as err:

            print(
                f"[news_images] cleanup failed: "
                f"{path} -> {err}"
            )
